// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: calculator.proto

package grpc_go_example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceCalculatorClient is the client API for ServiceCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceCalculatorClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	Prime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (ServiceCalculator_PrimeClient, error)
	Avg(ctx context.Context, opts ...grpc.CallOption) (ServiceCalculator_AvgClient, error)
}

type serviceCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCalculatorClient(cc grpc.ClientConnInterface) ServiceCalculatorClient {
	return &serviceCalculatorClient{cc}
}

func (c *serviceCalculatorClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.ServiceCalculator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceCalculatorClient) Prime(ctx context.Context, in *PrimeRequest, opts ...grpc.CallOption) (ServiceCalculator_PrimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServiceCalculator_ServiceDesc.Streams[0], "/calculator.ServiceCalculator/Prime", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceCalculatorPrimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServiceCalculator_PrimeClient interface {
	Recv() (*PrimeResponse, error)
	grpc.ClientStream
}

type serviceCalculatorPrimeClient struct {
	grpc.ClientStream
}

func (x *serviceCalculatorPrimeClient) Recv() (*PrimeResponse, error) {
	m := new(PrimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceCalculatorClient) Avg(ctx context.Context, opts ...grpc.CallOption) (ServiceCalculator_AvgClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServiceCalculator_ServiceDesc.Streams[1], "/calculator.ServiceCalculator/Avg", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceCalculatorAvgClient{stream}
	return x, nil
}

type ServiceCalculator_AvgClient interface {
	Send(*AVGRequest) error
	CloseAndRecv() (*AVGResponse, error)
	grpc.ClientStream
}

type serviceCalculatorAvgClient struct {
	grpc.ClientStream
}

func (x *serviceCalculatorAvgClient) Send(m *AVGRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *serviceCalculatorAvgClient) CloseAndRecv() (*AVGResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AVGResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceCalculatorServer is the server API for ServiceCalculator service.
// All implementations must embed UnimplementedServiceCalculatorServer
// for forward compatibility
type ServiceCalculatorServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	Prime(*PrimeRequest, ServiceCalculator_PrimeServer) error
	Avg(ServiceCalculator_AvgServer) error
	mustEmbedUnimplementedServiceCalculatorServer()
}

// UnimplementedServiceCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedServiceCalculatorServer struct {
}

func (UnimplementedServiceCalculatorServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedServiceCalculatorServer) Prime(*PrimeRequest, ServiceCalculator_PrimeServer) error {
	return status.Errorf(codes.Unimplemented, "method Prime not implemented")
}
func (UnimplementedServiceCalculatorServer) Avg(ServiceCalculator_AvgServer) error {
	return status.Errorf(codes.Unimplemented, "method Avg not implemented")
}
func (UnimplementedServiceCalculatorServer) mustEmbedUnimplementedServiceCalculatorServer() {}

// UnsafeServiceCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCalculatorServer will
// result in compilation errors.
type UnsafeServiceCalculatorServer interface {
	mustEmbedUnimplementedServiceCalculatorServer()
}

func RegisterServiceCalculatorServer(s grpc.ServiceRegistrar, srv ServiceCalculatorServer) {
	s.RegisterService(&ServiceCalculator_ServiceDesc, srv)
}

func _ServiceCalculator_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCalculatorServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.ServiceCalculator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCalculatorServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceCalculator_Prime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceCalculatorServer).Prime(m, &serviceCalculatorPrimeServer{stream})
}

type ServiceCalculator_PrimeServer interface {
	Send(*PrimeResponse) error
	grpc.ServerStream
}

type serviceCalculatorPrimeServer struct {
	grpc.ServerStream
}

func (x *serviceCalculatorPrimeServer) Send(m *PrimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ServiceCalculator_Avg_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ServiceCalculatorServer).Avg(&serviceCalculatorAvgServer{stream})
}

type ServiceCalculator_AvgServer interface {
	SendAndClose(*AVGResponse) error
	Recv() (*AVGRequest, error)
	grpc.ServerStream
}

type serviceCalculatorAvgServer struct {
	grpc.ServerStream
}

func (x *serviceCalculatorAvgServer) SendAndClose(m *AVGResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *serviceCalculatorAvgServer) Recv() (*AVGRequest, error) {
	m := new(AVGRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServiceCalculator_ServiceDesc is the grpc.ServiceDesc for ServiceCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.ServiceCalculator",
	HandlerType: (*ServiceCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _ServiceCalculator_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Prime",
			Handler:       _ServiceCalculator_Prime_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Avg",
			Handler:       _ServiceCalculator_Avg_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculator.proto",
}
