// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: calculator.proto

package grpc_go_example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceCalculatorClient is the client API for ServiceCalculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceCalculatorClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
}

type serviceCalculatorClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceCalculatorClient(cc grpc.ClientConnInterface) ServiceCalculatorClient {
	return &serviceCalculatorClient{cc}
}

func (c *serviceCalculatorClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.ServiceCalculator/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceCalculatorServer is the server API for ServiceCalculator service.
// All implementations must embed UnimplementedServiceCalculatorServer
// for forward compatibility
type ServiceCalculatorServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	mustEmbedUnimplementedServiceCalculatorServer()
}

// UnimplementedServiceCalculatorServer must be embedded to have forward compatible implementations.
type UnimplementedServiceCalculatorServer struct {
}

func (UnimplementedServiceCalculatorServer) Sum(context.Context, *SumRequest) (*SumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedServiceCalculatorServer) mustEmbedUnimplementedServiceCalculatorServer() {}

// UnsafeServiceCalculatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceCalculatorServer will
// result in compilation errors.
type UnsafeServiceCalculatorServer interface {
	mustEmbedUnimplementedServiceCalculatorServer()
}

func RegisterServiceCalculatorServer(s grpc.ServiceRegistrar, srv ServiceCalculatorServer) {
	s.RegisterService(&ServiceCalculator_ServiceDesc, srv)
}

func _ServiceCalculator_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceCalculatorServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.ServiceCalculator/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceCalculatorServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceCalculator_ServiceDesc is the grpc.ServiceDesc for ServiceCalculator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceCalculator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.ServiceCalculator",
	HandlerType: (*ServiceCalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _ServiceCalculator_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator.proto",
}
